name: "Close Stale Issues"

on:
  schedule:
    - cron: "0 15,22 * * 1-5"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0
        with:
          days-before-stale: 7
          days-before-issue-stale: -1
          days-before-close: 3
          exempt-pr-labels: "on hold"
          stale-pr-message: >
            This PR has been marked as stale after 7 or more days of inactivity.
            Please have a maintainer add the `on hold` label if this PR should remain open.
            If there is no further activity or the `on hold` label is not added, this PR will be closed in 3 days.
